services:
  Dbp\Relay\CabinetConnectorCampusonlineBundle\Service\:
    resource: '../../Service'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetConnectorCampusonlineBundle\Command\:
    resource: '../../Command'
    autowire: true
    autoconfigure: true
