services:
  Dbp\Relay\CabinetConnectorCampusonlineBundle\Service\:
    resource: '../../Service'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetConnectorCampusonlineBundle\Command\:
    resource: '../../Command'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CabinetConnectorCampusonlineBundle\Command\SyncCommand:
    autowire: true
    autoconfigure: true
    calls:
      - setCache: [ '@dbp.relay.cabinet_connector_campusonline.cache.sync' ]

  Dbp\Relay\CabinetConnectorCampusonlineBundle\Command\SyncOneCommand:
    autowire: true
    autoconfigure: true
    calls:
      - setCache: [ '@dbp.relay.cabinet_connector_campusonline.cache.sync' ]

  dbp.relay.cabinet_connector_campusonline.cache.sync:
    parent: cache.app
    tags:
      - { name: 'cache.pool', default_lifetime: 60 }

  Dbp\Relay\CabinetConnectorCampusonlineBundle\SyncApi\PersonSync:
    autowire: true
    autoconfigure: true
    calls:
      - setCache: [ '@dbp.relay.cabinet_connector_campusonline.cache.sync' ]

  Dbp\Relay\CabinetBundle\PersonSync\PersonSyncInterface:
    '@Dbp\Relay\CabinetConnectorCampusonlineBundle\SyncApi\PersonSync'
